theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true
cursorline = true
end-of-line-diagnostics = "hint"
line-number = "relative"
trim-trailing-whitespace = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-inlay-hints = true

[editor.soft-wrap]
enable = true

[keys.normal]
A-b = "move_prev_sub_word_start"
A-e = "move_next_sub_word_end"
A-h = "move_parent_node_start"
A-l = "move_parent_node_end"
A-w = "move_next_sub_word_start"
X = "extend_line_above"

[keys.select]
A-b = "extend_prev_sub_word_start"
A-e = "extend_next_sub_word_end"
A-h = "extend_parent_node_start"
A-l = "extend_parent_node_end"
A-w = "extend_next_sub_word_start"
X = "extend_line_above"
